In [1]:
my_list = [1, 2, 3]

In [2]:
my_list

[1, 2, 3]

In [5]:
import numpy as np

In [7]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [ ]:
# Trying '^='

In [10]:
two_d_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
two_d_array = np.array(two_d_list)
two_d_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.arange(0, 10, 2, dtype=int)
# Array Range

array([0, 2, 4, 6, 8])

In [25]:
np.zeros((3, 2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [26]:
np.ones((3, 1, 2))

array([[[ 1.,  1.]],

       [[ 1.,  1.]],

       [[ 1.,  1.]]])