In [1]:
import numpy as np


In [4]:
np.matrix('1,2;3,4')

matrix([[1, 2],
        [3, 4]])

In [9]:
x = np.array([1, 3, 2, 4])

In [10]:
x.shape

(4,)

In [11]:
y = x[None, :]

In [12]:
y.shape

(1, 4)

In [13]:
y

array([[1, 3, 2, 4]])

In [14]:
z = x[:, None]

In [15]:
z

array([[1],
       [3],
       [2],
       [4]])

In [17]:
lm = x.reshape(2, 2)

In [18]:
lm

array([[1, 3],
       [2, 4]])

In [35]:
# Fortran Ordering
X = np.arange(0, 25, 3).reshape((3, 3), order='F')

In [36]:
Y = X.reshape(3, 3)

In [37]:
X

array([[ 0,  9, 18],
       [ 3, 12, 21],
       [ 6, 15, 24]])

In [38]:
X[1]

array([ 3, 12, 21])

In [39]:
X[2][2]

24

In [46]:
g = np.array([1, 2, 3]).reshape(1, 3)

In [47]:
g

array([[1, 2, 3]])

In [48]:
g * X 

array([[ 0, 18, 54],
       [ 3, 24, 63],
       [ 6, 30, 72]])

In [58]:
g

array([[1, 2, 3]])

In [60]:
g = g.reshape(3, 1)

In [61]:
g

array([[1],
       [2],
       [3]])

In [67]:
X

array([[ 0,  9, 18],
       [ 3, 12, 21],
       [ 6, 15, 24]])